# Site settings
title: opgenorth.net
email: tom@opgenorth.net
description: > # this means to ignore newlines until "baseurl:"
  Mindless missives of a programmer from the North. Sometimes programming, sometimes other things, sometimes interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opgenorth.net" # the base hostname & protocol for your site
twitter_username: topgenorth
github_username:  topgenorth

# Build settings
markdown: kramdown
