# Site settings
title: opgenorth.net
email: tom@opgenorth.net
description: > # this means to ignore newlines until "baseurl:"
  Mindless missives of a programmer from the North. Sometimes programming, sometimes other things, sometimes interesting.
baseurl: "/jekyll-github-actions"
#baseurl: "" # the subpath of your site, e.g. /blog/blog
url: "http://www.opgenorth.net" # the base hostname & protocol for your site
twitter_username: topgenorth
github_username:  topgenorth
#theme: jekyll-theme-midnight

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Disqus Comments
disqus_short_name: opgenorthnet
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: 1812612

plugins:
  - jekyll-redirect-from


