version: '3'
services:
  jekyll-author:
    image: jekyll/jekyll
    container_name: myblog
    entrypoint: jekyll serve --drafts --watch
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll

  myblog-optimize-images:
    build:
      context: .
      dockerfile: Dockerfile-optimize-images
    container_name: myblog-optimize-images
    volumes:
      - .:/srv/jekyll
    command:
      - /bin/sh
      - -c
      - |
        find . -type f -name '*.png' -exec optipng -o7 -strip all '{}' \;
        find . -name "*.jpg" -exec jpegoptim  --strip-all '{}' \;
