FROM nginx
ARG GIT_COMMIT
EXPOSE 4040 80

RUN mkdir -p /var/www/partnerdocs
WORKDIR /var/www/partnerdocs
RUN mkdir -p /opt/basic_auth
RUN rm /etc/nginx/conf.d/default.conf

COPY _config/opt/basic_auth/.htpasswd /opt/basic_auth/.htpasswd
COPY _config/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

LABEL git_commit=$GIT_COMMIT
COPY _site /var/www/partnerdocs
